name: 'Android Build'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  # secrets:
  #     DOCKERHUB_USERNAME:
  #       required: true
  #     DOCKERHUB_TOKEN:
  #       required: true
jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # - name: Set Up JDK
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: '17'
      #     cache: 'gradle'
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 21.6.1
          cache: 'npm'

      # - name: Install dependencies
      #   run: npm install
      # - name: Make Gradlew Executable
      #   run: cd android && chmod +x ./gradlew
      # - name: Build Android

      #   run: |
      #     cd android && gradle init && gradle wrapper

      # - name: Cache Gradle Dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.gradle/caches
      #     key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gradle-caches-

      # - name: Build Android
      #   run: bash -l -c 'cd android && ./gradlew bundleRelease'

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build  and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: sankeerthanasuddala/connect-demo-android
