name: Continuous Integration for Mobile

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # - name: Install dependencies
      #   run: npm install

      # - name: Install Jest
      #   run: npm install --save-dev jest

    # - name: Linting
    #   run: npm run lint

    # - name: Run Unit tests
    #   run: npm test

  build-android:
    needs: install-and-test
    uses: ./.github/workflows/android-build.yml
    secrets: inherit
  # build-ios:
  #   needs: install-and-test
  #   uses: ./.github/workflows/ios-build.yml
